<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <link rel="stylesheet" href="<?php echo $this->getThemeCssPath(); ?>style.css">
    <title>BeC F.I.U Portal </title>
</head>
<body>
<div class="centered-text"><h1>BeC Internal Resource</h1></div>
<div class="navigation"><?php echo $this->renderTemplate('navigation'); ?></div>
