<div class="login-page">
    <div class="form">
        <form class="login-form" method="POST" action="">
            <input type="text" name="email" placeholder="E-mail"/>
            <input type="password" name="password" placeholder="password"/>
            <input type="hidden" name="login" value="true"/>
            <button>LOGIN</button>
            <p class="message">Not registered? <a href="<?php echo Runner::getUrl('login/register') ?>">Create an account</a></p>
        </form>
    </div>
</div>
