
<div class="login-page">
    <div class="form">
        <form class="login-form" method="POST" action="#">
            <input type="text" name="firstname" placeholder="First Name"/>
            <input type="text" name="lastname" placeholder="Last Name"/>
            <input type="password" name="password" placeholder="password"/>
            <input type="text" name="email" placeholder="email address"/>
            <input type="hidden" name="form" value="register"/>
            <button>create</button>
            <p class="message">Registered? <a href="#">Go to Login Form</a></p>
        </form>
    </div>
</div>