<div class="login-page">
    <div class="form">
        <form class="login-form" method="POST" action="<?php echo Runner::getUrl('login/registerPost') ?>">
            <input type="text" name="firstname" placeholder="First Name"/>
            <input type="text" name="lastname" placeholder="Last Name"/>
            <input type="password" name="password" placeholder="password"/>
            <input type="text" name="email" placeholder="email address"/>
            <input type="hidden" name="register" value="true"/>
            <button>create</button>
            <p class="message">Registered? <a href="<?php echo Runner::getUrl('login') ?>">Go to Login Form</a></p>
        </form>
    </div>
</div>

<script>
    var close = document.getElementsByClassName("closebtn");
    var i;

    for (i = 0; i < close.length; i++) {
        close[i].onclick = function () {
            var div = this.parentElement;
            div.style.opacity = "0";
            setTimeout(function () {
                div.style.display = "none";
            }, 600);
        }
    }
</script>